# Generated by Django 4.0.5 on 2022-06-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('nickname', models.CharField(max_length=30)),
                ('mbti', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MBTI',
        ),
    ]
