# Generated by Django 4.0.5 on 2022-06-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_delete_mbti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
